
services:

  postgres:
    image: postgres:16

    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - microservice-network
  mongodb:
    image: mongo:latest
    container_name: mongodb-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  rabbitmq:
    image: rabbitmq:3-management

    container_name: rabbitmq

    restart: always

    ports:
      - "5672:5672"
      - "15672:15672"

    networks:
      - microservice-network


  user-service:
    build:
      context: ./user-service

    container_name: user-service

    restart: always

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: mongodb://@mongodb-db:27017/user_management
      RABITMQ_URL: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: changeme

    depends_on:
      - mongodb
      - rabbitmq

    networks:
      - microservice-network


  task-service:
    build:
      context: ./task-service

    container_name: task-service

    restart: always

    ports:
      - "8002:8000"

    environment:
      DATABASE_URL: postgresql://postgres:password@postgres-db:5432/taskdb
      RABIT_MQ_URL: amqp://guest:guest@rabbitmq:5672
      JWT_SECRET: changeme

    depends_on:
      - postgres
      - rabbitmq

    networks:
      - microservice-network


  notification-service:
    build:
      context: ./notification-service

    container_name: notification-service

    restart: always

    ports:
      - "8003:8000"

    environment:
      RABBITMQ_URL:  amqp://guest:guest@rabbitmq:5672

    depends_on:
      - rabbitmq

    networks:
      - microservice-network


volumes:
  postgres_data:
  mongo_data:



networks:
  microservice-network:
    driver: bridge